### ISSUE TITLE
issue with saving the data to the knowledge

### ISSUE THREAD

**Issue by kkailaasa** [rainchen/dify-tool-LongTermMemory#2]
hi. I tested this feature and it is really great and has many use cases but i was facing an error where when it saved the data to the document it was saving 1 users content to new chunks every time not like how you showed in the video where it saved all the set of questions to the same chunk. i didnt do any customization but i was getting this result. the only thing i changed was the llm. i didnt have  deepsee so i used gpt4o. hope you are able to take a look at this error

**Comment by rainchen** [comment]
First, try changing the Temperature parameter for gpt4o LLM, use a lower or higher value. 

If not working, try this:
the `update_user_memory` or `add_user_memory` action is determined by prompt ["Parameter Extraction"](https://github.com/rainchen/dify-tool-LongTermMemory/blob/main/agent-prompt.md#extracting-the-action-parameter)
you can try to adjust the prompt content which was set in `Agent prompt` node

**Comment by rainchen** [comment]
@kkailaasa Is the problem solved?

**Comment by jorgearone** [comment]
Hi! First of all, thanks for the great contribution to the community, secondly, I thought that all the configuration could be done in "Dify Cloud" but apparently I have to have the dify self hosted (I have no programming skills).

Question, is there a way to use it only in the dify cloud?

on the other hand, in case I dare to try to self-host dify on my computer, how could I avoid installing the dependencies (I always had problems with this) I imagine that by now there will be more flexible no-code solutions. 

I read you.

**Comment by rainchen** [comment]
@jorgearone 
This should work in Dify Cloud, checkout Dify document at https://docs.dify.ai/guides/knowledge-base/maintain-dataset-via-api
You can see that base url of Dify Cloud Knowledge API is `https://api.dify.ai` , use this as the `base_url` parameter value. If this works I will add this note in the README.

**Comment by jorgearone** [comment]
Yes! someone helped me to identify it, what happens is that in the tutorial it says connect to the internal docket, that led me to think that it had to be self-hosted.
 On the other hand.

I am going to try it again, on the other hand I was talking in the dify discord and they commented the following:

<<It seem like it is using Dify Knowledge's document segment as key-value database, I don't think that a good idea, "Knowledge" is made for RAG not KV...

Also, create or edit segment by API only work if:
you are paid user; or you are self host.

And even you passed that part, currently my Dify said the that "The maximum length of keyword is 20", and that causing all those issues.
So that DSL basically won't work >>

what do you think about it.

**Comment by rainchen** [comment]
> It seems like it is using Dify Knowledge's document segment as a key-value database, which I don't think is a good idea. "Knowledge" is designed for RAG, not KV...

Let's align on two fundamental concepts:
- To clarify what a RAG system does: it retrieves some data and loads them as part of the context for LLM prompting. What ever data from, it finally will be injected as part of a context of a LLM prompt message.
- Knowledge is not only static PDF/Word files; it also includes environmental/external information, such as searching results from search engines, query results from databases, etc.

This tool is not merely using Dify Knowledge as a K/V storage.

The idea behind this tool is to use Dify Knowledge document segments as dynamically updated documents for users.
The memory items and values are in K/V form so that they can be easily read/written by LLM and easily extracted by programming via API. You can check out the template content:

```
<UserInfo>
  <name>${user_name}</name>
  <age>${user_age}</age>
  <hobbies>${user_hobbies}</hobbies>
  <any_user_info>${any_user_info}</any_user_info>
</UserInfo>
```

and the actual saved content:

<img width="827" alt="Screenshot 2024-08-13 at 11 13 32" src="https://github.com/user-attachments/assets/e64544cc-e322-41bd-beeb-3562ff045861">

I don't believe that storing items/values in natural language form as "my xx is xxx" is the only way to define "Knowledge"

> Also, create or edit segment by API only work if:
> you are paid user; or you are self host.

I don't use Dify Cloud, I have no idea about this limitation.
If that is the case, this tool is currently only available for self-hosting.
It's quite easy to port to using other service that can saving/retrieving text since the request params of  "Action:retrieve_memory/add_memory/update_memory" nodes are quite simple.

about the "The maximum length of keyword is 20", I think this is a limitation for UI not for API, since the user-id can be saved as keyword successfully.

**Comment by jorgearone** [comment]
I understand, thanks for the clarification.

As I told you before, the dependencies installations have me crazy, that's why I use only the dify cloud platform.

However, I am thinking of taking it to an external database through an API, basically for the scalability of the space.
... any recommendations?

**Comment by rainchen** [comment]
install self-hosted Dify using docker-compose is quite easy, all you need is install docker, and there is a well-written guide for it:  https://docs.dify.ai/getting-started/install-self-hosted/docker-compose

about database service,  maybe you can try Firebase, it can handle JSON type data very well, checkout the document: https://firebase.google.com/docs/database/rest/save-data

**Comment by jorgearone** [comment]
> @jorgearone This should work in Dify Cloud, checkout Dify document at https://docs.dify.ai/guides/knowledge-base/maintain-dataset-via-api You can see that base url of Dify Cloud Knowledge API is `https://api.dify.ai` , use this as the `base_url` parameter value. If this works I will add this note in the README.

I just tried, and I get this error. any ideas?
![Cconfig memory](https://github.com/user-attachments/assets/563d5fa7-6cfe-44f5-858d-39f0d58fc5f0)
![memory](https://github.com/user-attachments/assets/d0f27a23-476e-4722-8c52-7084abdc5b72)

**Comment by rainchen** [comment]
@jorgearone should use `https://api.dify.ai`, without the "/v1". If still error, you need to run the "LongTermMemory" workflow to check the output of the failed "Action*" node.
You should create a new issue for the Dify cloud issue, since the topic is not relating to the original post. I'm closing this issue.
